// <auto-generated />
using System;
using EdifyApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EdifyApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190802103839_ExtendedUserClass")]
    partial class ExtendedUserClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("EdifyApp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CurrentOutstandingDuties");

                    b.Property<string>("Department");

                    b.Property<string>("FillInEmployeeReportsTo");

                    b.Property<DateTime>("LeaveCommencingDate");

                    b.Property<string>("LeaveReason");

                    b.Property<int>("NumberOfDays");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int>("RemainingLeaveDays");

                    b.Property<DateTime>("ReturnDate");

                    b.Property<string>("StatusOfCurrentOutstandingDuties");

                    b.Property<string>("TakeoverEmployee");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EdifyApp.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
